### ISSUE TITLE
Is it compatible with .net 4.5.2 ?

### ISSUE THREAD

**Issue by shridharng** [andijakl/universal-beacon#10]
I am getting following error when I tried to install the package.  
Install-Package : Could not install package 'Microsoft.NETCore.Platforms 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2'

**Comment by DPB61** [comment]
I am also having the same error:

"Could not install package 'Microsoft.NETCore.Platforms 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."
I have tried quite a few framework versions but cannot find the correct one.

**Comment by andijakl** [comment]
The new version of the library (3.0+) is now compatible to .NET Standard 1.3+.
This version of .NET Standard is supported by .NET 4.6+, see: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

It's possible that you could downgrade the library to .NET Standard 1.2, which would be compatible to .net 4.5.1+. This has not been tested so far.
