### ISSUE TITLE
Beacon Data Store

### ISSUE THREAD

**Issue by Hiranmayee24** [andijakl/universal-beacon#11]
Which file the beacon data gets stored ?And is there any API (Rest) for Bluetooth Beacon Interactor?

**Comment by andijakl** [comment]
Right now, the app does not export the captured data to a file - this is a planned feature, see #7 
The current implementation of the app shows the data on the screen. It also has code that you can activate to print the data to the debug output.

**Comment by sssw2** [comment]
#7
