### ISSUE TITLE
Is it posible with MS Hololens ?

### ISSUE THREAD

**Issue by sw-ms-ankitsangani** [andijakl/universal-beacon#12]

**Comment by andijakl** [comment]
Yes, actually the Bluetooth Beacon Interactor is available in the Store on HoloLens and works perfectly fine!

**Comment by sw-ms-ankitsangani** [comment]
Hi Andreas,

Thanks for your response i tried your app with HoloLens app integrate 
with unity3d and i got beacon response. Thanks once again thanks.

Cheers,
Ankit Sangani.
