### ISSUE TITLE
Add support for iOS

### ISSUE THREAD

**Issue by ctacke** [andijakl/universal-beacon#15]
We have support for UWP and Xamarin.Android.  We still need an iBluetoothPacketProvider implementation for iOS.

**Comment by frank10gm** [comment]
Hi! when do you plan to work on this?

**Comment by tribe84** [comment]
Would love to see this!

**Comment by dayvsonsales** [comment]
any plans?

**Comment by SwiftArchitect** [comment]
@ctacke : I would like to tackle the iOS port, unless you are close to a solution. Do you need help? Is there a prototype of sorts you would like to share?

**Comment by ctacke** [comment]
Nope, I've not even really started.  Feel free to implement it and submit a pull request.

**Comment by SwiftArchitect** [comment]
No problem.
I will check in progress in a work branch as I go.

Cheers

**Comment by SwiftArchitect** [comment]
Yes!

I have been tending to the Android side of things since my client has been
eager to see a prototype on that platform, and first wanted a proof of
concept. Done.

This to say that I am now more than ever motivated to tend to the iOS side,
which is scheduled within the next 2 weeks.

Xavier

**Comment by john-lanticse** [comment]
Any update on this?

**Comment by PaulVrugt** [comment]
@SwiftArchitect I'm also curious about any progress

**Comment by SwiftArchitect** [comment]
Work in progress. iOS integration can be viewed here:

https://github.com/SwiftArchitect/universal-beacon/tree/issue%2315-Add-support-for-iOS

**Comment by SwiftArchitect** [comment]
Pull request submitted.

**Comment by bastou2316** [comment]
Has master or any other branch been maintained to catch up with up-to-date Xamarin.Forms? Yes the master branch from andijakl works fine.

**Comment by andijakl** [comment]
I'll check the latest status and merge / document everything in the following days!

**Comment by SwiftArchitect** [comment]
Fantastic

**Comment by Olivier-B** [comment]
Hi,

Very interested in a generic (provider's agnostic) component to iBeacons and EddyStones for all 3 Xamarin (UWP, Android & iOS).

I integrated UWP & Android and build fine. Now I have to do some tests to received the packages, map to the frames and to look for updates.

I really miss the iOS part. 80% devices are Androis, 17% iOS and the rest is other :-)
👍 

Olivier

**Comment by bastou2316** [comment]
I'm looking foward for the updates :)

**Comment by SwiftArchitect** [comment]
Still waiting for the PR approval I believe

**Comment by andijakl** [comment]
Checked the code today - generally looks excellent, great work!
Posted some comments and a few commits in the pull request #23 . Can you please check the latest state?
