### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by premsonbaby** [andijakl/universal-beacon#16]
unable to build the project after clone.
looks like some old references are still there.

**Comment by andijakl** [comment]
Can you please provide more information, e.g. your environment, build output and which references are missing?

**Comment by premsonbaby** [comment]
My bad here the details.

Dev Machine: Windows 10
Environment:  VS 2017
Startup project : UniversalBeacon.Sample.Android

Compile Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\packages\Xamarin.Android.Support.Vector.Drawable.23.3.0\build\Xamarin.Android.Support.Vector.Drawable.targets.	UniversalBeacon.Sample.Android	C:\Users\pbaby\Source\Repos\universal-beacon\Samples\UniversalBeacon.Sample\UniversalBeacon.Sample.Android\UniversalBeacon.Sample.Android.csproj	91	


Tried to restore package etc... still getting the same error.



![error](https://user-images.githubusercontent.com/31508228/29921615-34e4b0d8-8e4a-11e7-8ca3-cb688d4184e5.png)

**Comment by andijakl** [comment]
What version of Visual Studio exactly are you using? Are all depending tools fully updated (e.g., NuGet Package Manager, Xamarin)?
The Xamarin projects use the latest method of referencing packages, and no longer the packages.config file (also see: https://forums.xamarin.com/discussion/85051/project-references-nuget-packages-missing-on-this-computer )

**Comment by premsonbaby** [comment]
![image](https://user-images.githubusercontent.com/31508228/29923154-5ca7b3c6-8e50-11e7-8438-21cf67b47852.png)

**Comment by ctacke** [comment]
I've updated the project in source control, which eliminates this issue.

**Comment by premsonbaby** [comment]
Issue Fixed.
