### ISSUE TITLE
Configurable "BluetoothLEAdvertisementWatcher"

### ISSUE THREAD

**Issue by MarcorOnline** [andijakl/universal-beacon#17]
Hello.
Can you add the possibility to provide the **BluetoothLEAdvertisementWatcher** instance in the **WindowsBluetoothPacketProvider** constructor? 

I need to configure **SignalStrengthFilter** and currently I'm using reflection:

```
_windowsBluetoothPacketProvider = new WindowsBluetoothPacketProvider();
_beaconManager = new BeaconManager(_windowsBluetoothPacketProvider);
var field = typeof(WindowsBluetoothPacketProvider).GetField("_watcher", BindingFlags.NonPublic | BindingFlags.Instance);
var watcher = (BluetoothLEAdvertisementWatcher) field.GetValue(_windowsBluetoothPacketProvider);

watcher.SignalStrengthFilter ... (etc)
```
 
I thin that can be very usefull.

Best regards
Marco

**Comment by ctacke** [comment]
Take a look at this PR:

https://github.com/andijakl/universal-beacon/pull/18

**Comment by MarcorOnline** [comment]
@ctacke I've looked at the PR and I think that is perfect 👍 

Thanks
