### ISSUE TITLE
Is it possible to use this in Unity3D?

### ISSUE THREAD

**Issue by rob-alem** [andijakl/universal-beacon#19]
I am trying to make a HoloLens app. What I like to achieve is that my app reads the uuid of a bluetooth beacon. Then, it will get data from a database using the uuid. I already setted up my database, API and UI but I am unable to detect BLE beacons, which is the last vital part of my app.

Is it possible to use this library in some way to achieve this in Unity3D?

**Comment by andijakl** [comment]
In general, the UWP example app works fine on the HoloLens and is able to discover the beacons.
As such, it should in general also work through Unity. In another project, I've used Bluetooth LE on the HoloLens directly in a Unity 3D project.
Did you already try to add the library to your Unity 3D project - any issues you experienced?

**Comment by rob-alem** [comment]
Hi @andijakl, thank you very much for commenting.

After all the solution for detecting the beacons with HoloLens was permission related. You can find it [on StackOverflow](https://stackoverflow.com/questions/46607707/how-to-detect-ble-beacons-on-unity3d-hololens-app). Still can't believe that I oversaw this little checkbox, but I guess that is due to my lack of experience.

Thanks anyway, because I learned alot from this library.
