### ISSUE TITLE
Windows 10 App source code ?

### ISSUE THREAD

**Issue by apcloic** [andijakl/universal-beacon#5]
Hi,
Many thanks for this cool library.
Where do I find your Windows 10 app source code ?
How to import in Visual Studio ?
Regards,

**Comment by andijakl** [comment]
Hi,
thanks, glad you like the library!

The Windows 10 example app source code is part of the repository: https://github.com/andijakl/universal-beacon/tree/master/WindowsBeacons

To open the project in Visual Studio, clone the complete universal-beacon repository using GitHub Desktop, other GIT-software like TortoiseGit, or directly using Visual Studio 2015 which has Git support built-in - it gets even easier if you install the optional GitHub Extension for Visual Studio: https://visualstudio.github.com/

**Comment by apcloic** [comment]
@andijakl Thanks a lot Andreas, it works great with github extension for VS.
