### ISSUE TITLE
No Beacon Notifications

### ISSUE THREAD

**Issue by JpEncausse** [andijakl/universal-beacon#6]
Hi,
- I follow Windows 10 configuration steps, 
- I also try the Windows Discover Universal App

But I can't see any iBeacon. My configuration seems ok because I see my mobile in BLE, And my mobile see Beacons.

Any ideas ? or logs ?

**Comment by andijakl** [comment]
I've tested iBeacons mainly with beacons from kontakt.io - these are shown in the sample app, both on a Windows 10 Mobile device as well as on a PC. Does the app discover any other Bluetooth LE devices? Which device are you using to scan for beacons? Did you already try debugging the app and setting a breakpoint to check e.g., the MAC addresses of the discovered devices to find out if the Windows APIs don't deliver any information about the beacon, or if it gets lost in further processing steps by the app?

**Comment by JpEncausse** [comment]
I use an other BLE Dongle and now it works ! Thanks !
